// Generated by https://quicktype.io

export interface AcncClassificationSummary {
  classie_id: string;
  name: string;
  description: string;
  has_children: boolean;
  parent_id: string;
  parent_list: { [key: string]: string };
}
