// Generated by https://quicktype.io

export interface AcncCharitySummary {
  // Added locally for tracking purposes
  dateScraped: Date;
  version: number;
  // Api Properties
  classie_id: string;
  charity_uuid: string;
  charity_name: string;
  program_uuid: string;
  program_name: string;
  location_uuid: string;
  address: string;
  marker: string;
  distance: string;
  classie_label: string;
}
